apiVersion: batch/v1
kind: Job
metadata:
  name: mxpc-cli-installer
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      serviceAccountName: mxpc-cli-installer-sa
      initContainers:
        - command:
          - sh
          - -c
          - cd /workspace;mkdir home;cd home;
            wget {{ .Values.mxpcPath }}/mxpc-cli-{{ .Values.mendixOperatorVersion }}-linux-amd64.tar.gz;
            tar xvf mxpc-cli-{{ .Values.mendixOperatorVersion }}-linux-amd64.tar.gz;
          image: alpine
          name: download
          volumeMounts:
          - mountPath: /workspace
            name: workspace
      containers:
        - name: mxpc-cli-installer
          image: {{ .Values.image }}
          command:
            - sh
            - -c
            - cd /workspace/home; /mxpc-cli-installer-script
          volumeMounts:
            - mountPath: /workspace
              name: workspace
            - name: mxpc-cli-installer-script
              mountPath: /mxpc-cli-installer-script
              subPath: mxpc-cli-installer-script
            - name: mendix-installer-config-file
              mountPath: /mendix-installer-config-file
              readOnly: true
      volumes:
        - emptyDir: {}
          name: workspace
        - name: mxpc-cli-installer-script
          configMap:
            name: mxpc-cli-installer-script
            defaultMode: 0777
        - name: mendix-installer-config-file
          secret:
            secretName: mendix-installer-config-file
      restartPolicy: Never
