apiVersion: v1
kind: Secret
metadata:
  name: mendix-installer-config-file
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mendix-installer-config-file: |
    namespace: {{ .Values.namespace }}
    cluster_mode: standalone
    mask:
      database_plan: true
      storage_plan: true
      ingress: true
      registry: true
      proxy: false
      custom_tls: false
    database_plan:
      name: {{ .Values.database_plan.name }}
      type: postgres
      postgres:
        databaseprops:
          host: {{ .Values.database_plan.host }}
          port: 5432
          user: {{ .Values.database_plan.user }}
          password: {{ .Values.database_plan.password }}
          strict_tls: false
        db_name: {{ .Values.database_plan.db_name }}
        authentication_mode: static
        aws_iam_role: ""
        kubernetes_service_account: ""
    storage_plan:
      name: {{ .Values.storage_plan.name }}
      type: minio
      minio:
        endpoint: {{ .Values.storage_plan.endpoint }}
        accesskey: {{ .Values.storage_plan.accesskey }}
        secretkey: {{ .Values.storage_plan.secretkey }}
    ingress:
      type: kubernetes-ingress
      enable_tls: {{ .Values.ingress.enable_tls }}
      k8s_ingress:
        domain: {{ .Values.ingress.domainName }}
        useCustomIngressClass: true
        customIngressClass: nginx
        customIngressClassAsAnnotation: false
        path: /
      service: null
    registry:
      type: generic
      generic_registry:
        auth_pull_url: {{ .Values.registry.url }}
        auth_push_url: {{ .Values.registry.url }}
        registry_name: {{ .Values.registry.registry_name }}
        enable_auth: {{ .Values.registry.enable_auth }}
        auth_user: {{ .Values.registry.auth_user | quote }}
        auth_password: {{ .Values.registry.auth_password | quote }}
        link_secret_to_service_account: true
