namespace: pmp-ns-1
cluster_mode: standalone
mask:
  database_plan: true
  storage_plan: true
  ingress: true
  registry: false
  proxy: false
  custom_tls: false
database_plan:
  name: post-db
  type: postgres
  postgres:
    databaseprops:
      host: postgres-shared-postgresql.pmp-storage.svc.cluster.local
      port: 5432
      user: postgres
      password: Password1!
      strict_tls: false
    db_name: postgres
    authentication_mode: static
    aws_iam_role: ""
    kubernetes_service_account: ""
storage_plan:
  name: minio-st
  type: minio
  minio:
    endpoint: http://minio-shared.pmp-storage.svc.cluster.local:9000
    accesskey: minioadmin
    secretkey: Password1!
ingress:
  type: kubernetes-ingress
  enable_tls: false
  k8s_ingress:
    domain: mx4pc.nl
    useCustomIngressClass: true
    customIngressClass: nginx
    customIngressClassAsAnnotation: true
    path: /
  service: null
registry:
  type: generic
  generic_registry:
    auth_pull_url: localhost:5001
    auth_push_url: kind-registry:5000
    registry_name: registry
    enable_auth: false
    link_secret_to_service_account: false
custom_tls:
  ca_certificates_secret_name: registry-secret
  namespace: pmp-ns
