namespace: pmp-ns-1
cluster_mode: connected
mask:
  database_plan: true
  storage_plan: true
  ingress: true
  registry: true
  proxy: false
  custom_tls: false
database_plan:
  name: post-db
  type: postgres
  postgres:
    databaseprops:
      host: postgres-shared-postgresql.pmp-storage.svc.cluster.local
      port: 5432
      user: postgres
      password: Password1!
      strict_tls: false
    db_name: postgres
    authentication_mode: static
    aws_iam_role: ""
    kubernetes_service_account: ""
storage_plan:
  name: minio-st
  type: minio
  minio:
    endpoint: http://minio-shared.pmp-storage.svc.cluster.local:9000
    accesskey: minioadmin
    secretkey: Password1!
ingress:
  type: service-only
  enable_tls: false
  k8s_ingress: null
  service:
    type: LoadBalancer
registry:
  type: generic
  generic_registry:
    auth_pull_url: localhost:5001
    auth_push_url: kind-registry.local:5000
    registry_name: registry
    enable_auth: false
    link_secret_to_service_account: false